version: '3.7'

services:
  db:
    container_name: mongodb
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD} # Команда для запуска Redis с требованием пароля
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  mongo_data:
  redis_data:

networks:
  backend:
